<?php
if (!defined('INDEX_AUTH')) { define('INDEX_AUTH', true); }
$currentMonth = date('Y-m');
?>
<div class="container-fluid py-3">
    <style>
        .assignment-timeline { display: grid; gap: .75rem; }
        .assignment-timeline-item { position: relative; border-left: 3px solid #2563eb; padding: .75rem .75rem .75rem 1rem; background: #f8fafc; }
        .assignment-timeline-item::before { content: ''; position: absolute; left: -8px; top: 1rem; width: 11px; height: 11px; border-radius: 50%; background: #2563eb; border: 2px solid #fff; }
        .assignment-progress { height: 6px; }
    </style>
    <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-4">
        <div><h4 class="fw-bold mb-1 text-primary"><i class="bi bi-sliders me-2"></i>Thiết lập 5S</h4><p class="text-muted small mb-0">Quản lý khu vực, ảnh chuẩn và phân công kiểm tra theo tháng.</p></div>
        <button class="btn btn-primary" type="button" onclick="newZone()"><i class="bi bi-plus-lg me-1"></i>Thêm khu vực</button>
    </div>
    <div class="row g-3">
        <div class="col-12 col-xl-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold">Danh sách khu vực</div><div id="zone-list" class="list-group list-group-flush"></div></div></div>
        <div class="col-12 col-xl-5"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-bold" id="zone-form-title">Khu vực mới</div><div class="card-body">
            <form id="zone-form" onsubmit="saveZone(event)"><input type="hidden" name="zone_id" id="zone_id">
                <div class="row g-2"><div class="col-5"><label class="form-label">Mã khu vực</label><input name="zone_code" id="zone_code" class="form-control" required></div><div class="col-7"><label class="form-label">Tên khu vực</label><input name="zone_name" id="zone_name" class="form-control" required></div></div>
                <div class="mb-2"><label class="form-label">Mã QR/NFC</label><input name="qr_code" id="qr_code" class="form-control" placeholder="Mặc định dùng mã khu vực"></div>
                <div class="mb-2"><label class="form-label">Ảnh layout</label><input name="layout_image" id="layout_image" class="form-control" value="resources/images/factory_layout.png"></div>
                <div class="mb-2"><label class="form-label">Mô tả</label><textarea name="description" id="description" class="form-control" rows="2"></textarea></div>
                <div class="row g-2"><div class="col-6"><label class="form-label text-success">Ảnh mẫu OK</label><input type="file" name="ok_reference_image" class="form-control" accept="image/*" required></div><div class="col-6"><label class="form-label text-danger">Ảnh mẫu NG</label><input type="file" name="ng_reference_image" class="form-control" accept="image/*" required></div></div>
                <div class="d-flex gap-2 mt-3"><button class="btn btn-primary" type="submit">Lưu khu vực</button><button class="btn btn-light" type="button" onclick="newZone()">Hủy</button></div>
            </form>
        </div></div></div>
    </div>
    <div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white fw-bold">Phân công kiểm tra theo tháng</div><div class="card-body"><form id="assignment-form" class="row g-2 align-items-end" onsubmit="saveAssignment(event)"><div class="col-12 col-md-3"><label class="form-label">Tháng</label><input class="form-control" type="month" name="month_year" id="assignment-month" value="<?php echo $currentMonth; ?>" onchange="loadAssignmentTimeline()" required></div><div class="col-12 col-md-3"><label class="form-label">Khu vực</label><select class="form-select" name="zone_id" id="assign-zone" required></select></div><div class="col-12 col-md-3"><label class="form-label">Người kiểm tra</label><select class="form-select" name="inspector_id" id="assign-inspector" required></select></div><div class="col-12 col-md-3"><label class="form-label">Người chịu trách nhiệm</label><select class="form-select" name="assignee_id" id="assign-assignee" required></select></div><div class="col-12"><button class="btn btn-outline-primary" type="submit"><i class="bi bi-save me-1"></i>Lưu phân công</button></div></form></div></div>
    <div class="card border-0 shadow-sm mt-3"><div class="card-header bg-white d-flex justify-content-between align-items-center"><strong>Timeline nhân viên đã phân công</strong><span class="small text-muted" id="timeline-month"></span></div><div class="card-body"><div id="assignment-timeline" class="assignment-timeline"><div class="text-muted">Đang tải phân công...</div></div></div></div>
</div>
<script>
let zoneData = [], userData = [];
document.addEventListener('DOMContentLoaded', loadSettings);
function loadSettings() { fetch('api/five_s_get_dashboard.php').then(r => r.json()).then(data => { zoneData = data.zones || []; userData = data.users || []; renderZones(); fillOptions(); loadAssignmentTimeline(); }); }
function renderZones() { const list = document.getElementById('zone-list'); list.innerHTML = zoneData.length ? '' : '<div class="p-3 text-muted">Chưa có khu vực.</div>'; zoneData.forEach(zone => { const row = document.createElement('button'); row.type = 'button'; row.className = 'list-group-item list-group-item-action d-flex justify-content-between align-items-center text-start'; row.innerHTML = `<span><strong>${escapeText(zone.zone_name)}</strong><small class="d-block text-muted">${escapeText(zone.zone_code)}</small></span><i class="bi bi-pencil"></i>`; row.onclick = () => editZone(zone); list.appendChild(row); }); }
function fillOptions() { document.getElementById('assign-zone').innerHTML = zoneData.map(z => `<option value="${z.id}">${escapeText(z.zone_name)} (${escapeText(z.zone_code)})</option>`).join(''); const options = userData.map(u => `<option value="${u.id}">${escapeText(u.fullname || u.username)}</option>`).join(''); document.getElementById('assign-inspector').innerHTML = options; document.getElementById('assign-assignee').innerHTML = options; }
function newZone() { document.getElementById('zone-form').reset(); document.getElementById('zone_id').value = ''; document.getElementById('layout_image').value = 'resources/images/factory_layout.png'; document.getElementById('zone-form-title').textContent = 'Khu vực mới'; document.querySelectorAll('#zone-form input[type=file]').forEach(input => input.required = true); }
function editZone(zone) { document.getElementById('zone_id').value = zone.id; document.getElementById('zone_code').value = zone.zone_code || ''; document.getElementById('zone_name').value = zone.zone_name || ''; document.getElementById('qr_code').value = zone.qr_code_hash || ''; document.getElementById('layout_image').value = zone.layout_image || ''; document.getElementById('description').value = zone.description || ''; document.getElementById('zone-form-title').textContent = 'Chỉnh sửa khu vực'; document.querySelectorAll('#zone-form input[type=file]').forEach(input => input.required = false); }
function saveZone(event) { event.preventDefault(); fetch('api/five_s_save_zone.php', { method: 'POST', body: new FormData(document.getElementById('zone-form')) }).then(r => r.json()).then(data => { alert(data.message); if (data.success) { loadSettings(); newZone(); } }); }
function saveAssignment(event) { event.preventDefault(); fetch('api/five_s_save_assignment.php', { method: 'POST', body: new FormData(document.getElementById('assignment-form')) }).then(r => r.json()).then(data => { alert(data.message); if (data.success) loadAssignmentTimeline(); }); }
function loadAssignmentTimeline() { const month = document.getElementById('assignment-month').value; fetch(`api/five_s_get_assignments.php?month=${encodeURIComponent(month)}`).then(r => r.json()).then(data => { document.getElementById('timeline-month').textContent = data.month || month; renderAssignmentTimeline(data.assignments || []); }); }
function renderAssignmentTimeline(assignments) { const timeline = document.getElementById('assignment-timeline'); if (!assignments.length) { timeline.innerHTML = '<div class="text-muted">Chưa có phân công trong tháng này.</div>'; return; } timeline.innerHTML = assignments.map(item => { const total = Number(item.total_days) || 0; const completed = Number(item.completed_days) || 0; const percent = total ? Math.round(completed * 100 / total) : 0; return `<div class="assignment-timeline-item"><div class="d-flex justify-content-between gap-2 flex-wrap"><strong>${escapeText(item.zone_name)} (${escapeText(item.zone_code)})</strong><span class="badge bg-primary-subtle text-primary">${escapeText(item.month_year)}</span></div><div class="small mt-2"><i class="bi bi-person-check me-1"></i>Kiểm tra: <strong>${escapeText(item.inspector_name || item.inspector_username || 'Chưa gán')}</strong></div><div class="small"><i class="bi bi-person-gear me-1"></i>Chịu trách nhiệm: <strong>${escapeText(item.assignee_name || item.assignee_username || 'Chưa gán')}</strong></div><div class="progress assignment-progress mt-2"><div class="progress-bar bg-success" style="width: ${percent}%"></div></div><div class="small text-muted mt-1">${completed}/${total} ngày đã hoàn thành · ${escapeText(item.first_date || '')} đến ${escapeText(item.last_date || '')}</div></div>`; }).join(''); }
function escapeText(value) { const node = document.createElement('span'); node.textContent = value || ''; return node.innerHTML; }
</script>
